version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/todo_db
      - JWT_SECRET=ReplaceWithASecretKey
    ports:
      - "5000:5000"
    depends_on:
      - mongo

volumes:
  mongo-data:
